name: 'Build components (new feature/change)'

on:
  push:
    branches:
      - "feature/*"

jobs:
  build-components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          npm install --force
          npm install react react-dom styled-components prop-types --save
      - name: Build components
        run: |
          npm run build